### ISSUE TITLE
Error: Failed to parse (unnamed) as a valid auto format key: Failed to auto-detect format of key

### ISSUE THREAD

**Issue by gustavomr** [oracle-actions/configure-kubectl-oke#26]
I´m trying to use github actions with oracle kubectl oke and I´m getting this error:
Error: Failed to parse (unnamed) as a valid auto format key: Failed to auto-detect format of key

main.yml:

 ```
CD:
    runs-on: ubuntu-latest
    name: Install Kubectl for OKE
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}

    steps:
      - name: Configure Kubectl
        uses: oracle-actions/configure-kubectl-oke@v1.3.2
        id: test-configure-kubectl-oke-action
        with:
          cluster: ${{ secrets.OKE_CLUSTER_OCID }}
          enablePrivateEndpoint: true

      - name: Run Kubectl
        run: kubectl get nodes -A
```

Full stack trace:

`2024-01-24T02:13:45.2977912Z Requested labels: ubuntu-latest
2024-01-24T02:13:45.2978260Z Job defined at: gustavomr/learning-k8s/.github/workflows/main.yml@refs/heads/main
2024-01-24T02:13:45.2978398Z Waiting for a runner to pick up this job...
2024-01-24T02:13:46.2149245Z Job is waiting for a hosted runner to come online.
2024-01-24T02:13:50.9450625Z Job is about to start running on the hosted runner: GitHub Actions 2 (hosted)
2024-01-24T02:13:53.9693822Z Current runner version: '2.311.0'
2024-01-24T02:13:53.9734923Z ##[group]Operating System
2024-01-24T02:13:53.9735934Z Ubuntu
2024-01-24T02:13:53.9736462Z 22.04.3
2024-01-24T02:13:53.9737337Z LTS
2024-01-24T02:13:53.9738167Z ##[endgroup]
2024-01-24T02:13:53.9738794Z ##[group]Runner Image
2024-01-24T02:13:53.9739426Z Image: ubuntu-22.04
2024-01-24T02:13:53.9739990Z Version: 20240116.3.0
2024-01-24T02:13:53.9741419Z Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240116.3/images/ubuntu/Ubuntu2204-Readme.md
2024-01-24T02:13:53.9744296Z Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240116.3
2024-01-24T02:13:53.9745711Z ##[endgroup]
2024-01-24T02:13:53.9746516Z ##[group]Runner Image Provisioner
2024-01-24T02:13:53.9747217Z 2.0.329.1
2024-01-24T02:13:53.9747991Z ##[endgroup]
2024-01-24T02:13:53.9749368Z ##[group]GITHUB_TOKEN Permissions
2024-01-24T02:13:53.9752298Z Contents: read
2024-01-24T02:13:53.9752975Z Metadata: read
2024-01-24T02:13:53.9754480Z Packages: read
2024-01-24T02:13:53.9755261Z ##[endgroup]
2024-01-24T02:13:53.9759858Z Secret source: Actions
2024-01-24T02:13:53.9760710Z Prepare workflow directory
2024-01-24T02:13:54.1204082Z Prepare all required actions
2024-01-24T02:13:54.1473535Z Getting action download info
2024-01-24T02:13:54.3980467Z Download action repository 'oracle-actions/configure-kubectl-oke@v1.3.2' (SHA:a6d8f9282001ae82efb0f6e640c66b2f3bd3f954)
2024-01-24T02:13:55.3389443Z Complete job name: Install Kubectl for OKE
2024-01-24T02:13:55.4730755Z ##[group]Run oracle-actions/configure-kubectl-oke@v1.3.2
2024-01-24T02:13:55.4732267Z with:
2024-01-24T02:13:55.4734338Z   cluster: ***
2024-01-24T02:13:55.4735351Z   enablePrivateEndpoint: true
2024-01-24T02:13:55.4736254Z env:
2024-01-24T02:13:55.4736960Z   OCI_CLI_USER: ***
2024-01-24T02:13:55.4738204Z   OCI_CLI_TENANCY: ***
2024-01-24T02:13:55.4739313Z   OCI_CLI_FINGERPRINT: ***
2024-01-24T02:13:55.4740403Z   OCI_CLI_KEY_CONTENT: ***
2024-01-24T02:13:55.4741108Z   OCI_CLI_REGION: ***
2024-01-24T02:13:55.4741705Z ##[endgroup]
2024-01-24T02:13:55.9155886Z ##[group]Installing Oracle Cloud Infrastructure CLI
2024-01-24T02:13:55.9159467Z [command]/usr/bin/python -m pip install oci-cli
2024-01-24T02:13:56.6457123Z Defaulting to user installation because normal site-packages is not writeable
2024-01-24T02:13:57.4535444Z Collecting oci-cli
2024-01-24T02:13:57.5654456Z   Downloading oci_cli-3.37.5-py3-none-any.whl (45.4 MB)
2024-01-24T02:13:58.1672775Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.4/45.4 MB 39.2 MB/s eta 0:00:00
2024-01-24T02:13:58.5358777Z Collecting python-dateutil<3.0.0,>=2.5.3
2024-01-24T02:13:58.5414450Z   Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
2024-01-24T02:13:58.5526010Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 KB 30.5 MB/s eta 0:00:00
2024-01-24T02:13:58.5565410Z Requirement already satisfied: six>=1.15.0 in /usr/lib/python3/dist-packages (from oci-cli) (1.16.0)
2024-01-24T02:13:58.6057587Z Collecting arrow>=1.0.0
2024-01-24T02:13:58.6111359Z   Downloading arrow-1.3.0-py3-none-any.whl (66 kB)
2024-01-24T02:13:58.6228977Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.4/66.4 KB 7.7 MB/s eta 0:00:00
2024-01-24T02:13:58.6261101Z Requirement already satisfied: pytz>=2016.10 in /usr/lib/python3/dist-packages (from oci-cli) (2022.1)
2024-01-24T02:13:58.6277951Z Requirement already satisfied: cryptography<42.0.0,>=3.2.1 in /usr/lib/python3/dist-packages (from oci-cli) (3.4.8)
2024-01-24T02:13:58.6290343Z Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from oci-cli) (2020.6.20)
2024-01-24T02:13:58.7565060Z Collecting oci==2.119.1
2024-01-24T02:13:58.7628882Z   Downloading oci-2.119.1-py3-none-any.whl (25.1 MB)
2024-01-24T02:13:59.0696115Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.1/25.1 MB 58.4 MB/s eta 0:00:00
2024-01-24T02:13:59.2631684Z Requirement already satisfied: PyYAML<=6.0.1,>=5.4 in /usr/lib/python3/dist-packages (from oci-cli) (5.4.1)
2024-01-24T02:13:59.3382305Z Collecting prompt-toolkit==3.0.29
2024-01-24T02:13:59.3458916Z   Downloading prompt_toolkit-3.0.29-py3-none-any.whl (381 kB)
2024-01-24T02:13:59.3557848Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.5/381.5 KB 52.5 MB/s eta 0:00:00
2024-01-24T02:13:59.3866256Z Collecting jmespath==0.10.0
2024-01-24T02:13:59.3913338Z   Downloading jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
2024-01-24T02:13:59.4235193Z Collecting terminaltables==3.1.0
2024-01-24T02:13:59.4304148Z   Downloading terminaltables-3.1.0.tar.gz (12 kB)
2024-01-24T02:13:59.4401637Z   Preparing metadata (setup.py): started
2024-01-24T02:14:00.0765959Z   Preparing metadata (setup.py): finished with status 'done'
2024-01-24T02:14:00.1208979Z Collecting click==8.0.4
2024-01-24T02:14:00.1255771Z   Downloading click-8.0.4-py3-none-any.whl (97 kB)
2024-01-24T02:14:00.1331026Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.5/97.5 KB 21.1 MB/s eta 0:00:00
2024-01-24T02:14:00.1364518Z Requirement already satisfied: pyOpenSSL<24.0.0,>=17.5.0 in /usr/lib/python3/dist-packages (from oci-cli) (21.0.0)
2024-01-24T02:14:00.1720867Z Collecting circuitbreaker<2.0.0,>=1.3.1
2024-01-24T02:14:00.1773457Z   Downloading circuitbreaker-1.4.0.tar.gz (9.7 kB)
2024-01-24T02:14:00.1882686Z   Preparing metadata (setup.py): started
2024-01-24T02:14:00.4430207Z   Preparing metadata (setup.py): finished with status 'done'
2024-01-24T02:14:00.4700450Z Collecting wcwidth
2024-01-24T02:14:00.4744629Z   Downloading wcwidth-0.2.13-py2.py3-none-any.whl (34 kB)
2024-01-24T02:14:00.5377801Z Collecting types-python-dateutil>=2.8.10
2024-01-24T02:14:00.5424200Z   Downloading types_python_dateutil-2.8.19.20240106-py3-none-any.whl (9.7 kB)
2024-01-24T02:14:00.6071655Z Building wheels for collected packages: terminaltables, circuitbreaker
2024-01-24T02:14:00.6081500Z   Building wheel for terminaltables (setup.py): started
2024-01-24T02:14:00.9628835Z   Building wheel for terminaltables (setup.py): finished with status 'done'
2024-01-24T02:14:00.9637777Z   Created wheel for terminaltables: filename=terminaltables-3.1.0-py3-none-any.whl size=15355 sha256=2325a849f0b7e1d36a05883201afe013f5bc4f2435c030b6de5c6fda6a8c3abe
2024-01-24T02:14:00.9641071Z   Stored in directory: /home/runner/.cache/pip/wheels/0e/e1/98/126eccfa07627229dd8299be9445fcf626f52e636268996bb6
2024-01-24T02:14:00.9660882Z   Building wheel for circuitbreaker (setup.py): started
2024-01-24T02:14:01.2713760Z   Building wheel for circuitbreaker (setup.py): finished with status 'done'
2024-01-24T02:14:01.2720499Z   Created wheel for circuitbreaker: filename=circuitbreaker-1.4.0-py3-none-any.whl size=7522 sha256=f09ce6bbcb1be39c7cf5203d555989e8aa9eb144cdf1631403d8287586b580b8
2024-01-24T02:14:01.2725894Z   Stored in directory: /home/runner/.cache/pip/wheels/3c/be/64/266b6ce2ef1130de5e419f04805acbb2df5a4ab1b91348f25b
2024-01-24T02:14:01.2737211Z Successfully built terminaltables circuitbreaker
2024-01-24T02:14:01.8031556Z Installing collected packages: wcwidth, terminaltables, circuitbreaker, types-python-dateutil, python-dateutil, prompt-toolkit, jmespath, click, oci, arrow, oci-cli
2024-01-24T02:14:32.5556170Z Successfully installed arrow-1.3.0 circuitbreaker-1.4.0 click-8.0.4 jmespath-0.10.0 oci-2.119.1 oci-cli-3.37.5 prompt-toolkit-3.0.29 python-dateutil-2.8.2 terminaltables-3.1.0 types-python-dateutil-2.8.19.20240106 wcwidth-0.2.13
2024-01-24T02:14:32.6842548Z ##[endgroup]
2024-01-24T02:14:32.6912984Z ##[error]Failed to parse (unnamed) as a valid auto format key: Failed to auto-detect format of key
2024-01-24T02:14:32.7487151Z Cleaning up orphan processes`

**Comment by Djelibeybi** [comment]
Are you running this on a self-hosted runner within OCI? The `enablePrivateEndpoint` option only works internally, not from a GitHub hosted runner.

**Comment by gustavomr** [comment]
> `enablePrivateEndpoint`

I´m using ubuntu-latest. I commented the line but the error is the same.

**Comment by Djelibeybi** [comment]
I'm not even sure where that error is coming from. Can you confirm this cluster has a public API endpoint that is accessible via the internet? Can you connect directly to it from your desktop, for example?

**Comment by gustavomr** [comment]
Yes! I´m able to connect to cluster even from oci client. 
I commented the line and I´m getting new error:
     OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}

Error: Failed to parse (unnamed) as a valid auto format key: Attempt to access memory outside buffer bounds

Maybe my secret is not appropriately configured. Could you help me on this? How can I get those values?

**Comment by Djelibeybi** [comment]
That should be the content of your `$HOME/.oci/oci_api_key.pem` file.

**Comment by gustavomr** [comment]
OK! I missconfigured the KEY_CONTET, but now getting on error that is not clear:

`2024-01-24T02:44:04.2773649Z Requested labels: ubuntu-latest
2024-01-24T02:44:04.2774053Z Job defined at: gustavomr/learning-k8s/.github/workflows/main.yml@refs/heads/main
2024-01-24T02:44:04.2774234Z Waiting for a runner to pick up this job...
2024-01-24T02:44:04.5913373Z Job is waiting for a hosted runner to come online.
2024-01-24T02:44:08.0827178Z Job is about to start running on the hosted runner: GitHub Actions 2 (hosted)
2024-01-24T02:44:10.6445008Z Current runner version: '2.311.0'
2024-01-24T02:44:10.6480691Z ##[group]Operating System
2024-01-24T02:44:10.6482223Z Ubuntu
2024-01-24T02:44:10.6483137Z 22.04.3
2024-01-24T02:44:10.6484045Z LTS
2024-01-24T02:44:10.6484906Z ##[endgroup]
2024-01-24T02:44:10.6485944Z ##[group]Runner Image
2024-01-24T02:44:10.6487045Z Image: ubuntu-22.04
2024-01-24T02:44:10.6487989Z Version: 20240116.3.0
2024-01-24T02:44:10.6490303Z Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240116.3/images/ubuntu/Ubuntu2204-Readme.md
2024-01-24T02:44:10.6493210Z Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240116.3
2024-01-24T02:44:10.6494973Z ##[endgroup]
2024-01-24T02:44:10.6496014Z ##[group]Runner Image Provisioner
2024-01-24T02:44:10.6497242Z 2.0.329.1
2024-01-24T02:44:10.6498104Z ##[endgroup]
2024-01-24T02:44:10.6500319Z ##[group]GITHUB_TOKEN Permissions
2024-01-24T02:44:10.6503103Z Contents: read
2024-01-24T02:44:10.6504293Z Metadata: read
2024-01-24T02:44:10.6505567Z Packages: read
2024-01-24T02:44:10.6506729Z ##[endgroup]
2024-01-24T02:44:10.6511589Z Secret source: Actions
2024-01-24T02:44:10.6512977Z Prepare workflow directory
2024-01-24T02:44:10.7896136Z Prepare all required actions
2024-01-24T02:44:10.8132186Z Getting action download info
2024-01-24T02:44:11.0275681Z Download action repository 'oracle-actions/configure-kubectl-oke@v1.3.2' (SHA:a6d8f9282001ae82efb0f6e640c66b2f3bd3f954)
2024-01-24T02:44:11.6194910Z Complete job name: Install Kubectl for OKE
2024-01-24T02:44:11.7438135Z ##[group]Run oracle-actions/configure-kubectl-oke@v1.3.2
2024-01-24T02:44:11.7439402Z with:
2024-01-24T02:44:11.7441153Z   cluster: ***
2024-01-24T02:44:11.7441940Z   enablePrivateEndpoint: false
2024-01-24T02:44:11.7442799Z env:
2024-01-24T02:44:11.7444309Z   OCI_CLI_USER: ***
2024-01-24T02:44:11.7446001Z   OCI_CLI_TENANCY: ***
2024-01-24T02:44:11.7447094Z   OCI_CLI_FINGERPRINT: ***
2024-01-24T02:44:11.7472253Z   OCI_CLI_KEY_CONTENT: ***
2024-01-24T02:44:11.7473153Z   OCI_CLI_REGION: ***
2024-01-24T02:44:11.7473962Z ##[endgroup]
2024-01-24T02:44:12.1444440Z ##[group]Installing Oracle Cloud Infrastructure CLI
2024-01-24T02:44:12.1451669Z [command]/usr/bin/python -m pip install oci-cli
2024-01-24T02:44:12.7545932Z Defaulting to user installation because normal site-packages is not writeable
2024-01-24T02:44:13.4779231Z Collecting oci-cli
2024-01-24T02:44:13.5888856Z   Downloading oci_cli-3.37.5-py3-none-any.whl (45.4 MB)
2024-01-24T02:44:14.4202353Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.4/45.4 MB 42.0 MB/s eta 0:00:00
2024-01-24T02:44:14.7852437Z Collecting python-dateutil<3.0.0,>=2.5.3
2024-01-24T02:44:14.7916177Z   Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
2024-01-24T02:44:14.8063146Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 KB 47.4 MB/s eta 0:00:00
2024-01-24T02:44:14.8065056Z Requirement already satisfied: pytz>=2016.10 in /usr/lib/python3/dist-packages (from oci-cli) (2022.1)
2024-01-24T02:44:14.8507801Z Collecting arrow>=1.0.0
2024-01-24T02:44:14.8586139Z   Downloading arrow-1.3.0-py3-none-any.whl (66 kB)
2024-01-24T02:44:14.8649825Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.4/66.4 KB 16.3 MB/s eta 0:00:00
2024-01-24T02:44:14.9131871Z Collecting click==8.0.4
2024-01-24T02:44:14.9231989Z   Downloading click-8.0.4-py3-none-any.whl (97 kB)
2024-01-24T02:44:14.9314600Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.5/97.5 KB 24.1 MB/s eta 0:00:00
2024-01-24T02:44:14.9562417Z Collecting terminaltables==3.1.0
2024-01-24T02:44:14.9640396Z   Downloading terminaltables-3.1.0.tar.gz (12 kB)
2024-01-24T02:44:14.9734670Z   Preparing metadata (setup.py): started
2024-01-24T02:44:15.2374069Z   Preparing metadata (setup.py): finished with status 'done'
2024-01-24T02:44:15.2386856Z Requirement already satisfied: pyOpenSSL<24.0.0,>=17.5.0 in /usr/lib/python3/dist-packages (from oci-cli) (21.0.0)
2024-01-24T02:44:15.2394170Z Requirement already satisfied: PyYAML<=6.0.1,>=5.4 in /usr/lib/python3/dist-packages (from oci-cli) (5.4.1)
2024-01-24T02:44:15.2402545Z Requirement already satisfied: cryptography<42.0.0,>=3.2.1 in /usr/lib/python3/dist-packages (from oci-cli) (3.4.8)
2024-01-24T02:44:15.3754519Z Collecting oci==2.119.1
2024-01-24T02:44:15.3885019Z   Downloading oci-2.119.1-py3-none-any.whl (25.1 MB)
2024-01-24T02:44:15.7085700Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.1/25.1 MB 52.9 MB/s eta 0:00:00
2024-01-24T02:44:15.9064645Z Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from oci-cli) (2020.6.20)
2024-01-24T02:44:15.9066931Z Requirement already satisfied: six>=1.15.0 in /usr/lib/python3/dist-packages (from oci-cli) (1.16.0)
2024-01-24T02:44:15.9926098Z Collecting prompt-toolkit==3.0.29
2024-01-24T02:44:16.0044990Z   Downloading prompt_toolkit-3.0.29-py3-none-any.whl (381 kB)
2024-01-24T02:44:16.0137264Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.5/381.5 KB 61.9 MB/s eta 0:00:00
2024-01-24T02:44:16.0441063Z Collecting jmespath==0.10.0
2024-01-24T02:44:16.0527502Z   Downloading jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
2024-01-24T02:44:16.0923882Z Collecting circuitbreaker<2.0.0,>=1.3.1
2024-01-24T02:44:16.1012774Z   Downloading circuitbreaker-1.4.0.tar.gz (9.7 kB)
2024-01-24T02:44:16.1107275Z   Preparing metadata (setup.py): started
2024-01-24T02:44:16.3274712Z   Preparing metadata (setup.py): finished with status 'done'
2024-01-24T02:44:16.3584777Z Collecting wcwidth
2024-01-24T02:44:16.3668721Z   Downloading wcwidth-0.2.13-py2.py3-none-any.whl (34 kB)
2024-01-24T02:44:16.4230478Z Collecting types-python-dateutil>=2.8.10
2024-01-24T02:44:16.4320492Z   Downloading types_python_dateutil-2.8.19.20240106-py3-none-any.whl (9.7 kB)
2024-01-24T02:44:16.4812750Z Building wheels for collected packages: terminaltables, circuitbreaker
2024-01-24T02:44:16.4823794Z   Building wheel for terminaltables (setup.py): started
2024-01-24T02:44:16.8017473Z   Building wheel for terminaltables (setup.py): finished with status 'done'
2024-01-24T02:44:16.8023336Z   Created wheel for terminaltables: filename=terminaltables-3.1.0-py3-none-any.whl size=15355 sha256=ac3ec2bf1a9f20c11c5b124fa9204751655e5edf197367e6650808937933180e
2024-01-24T02:44:16.8027816Z   Stored in directory: /home/runner/.cache/pip/wheels/0e/e1/98/126eccfa07627229dd8299be9445fcf626f52e636268996bb6
2024-01-24T02:44:16.8067201Z   Building wheel for circuitbreaker (setup.py): started
2024-01-24T02:44:17.0830186Z   Building wheel for circuitbreaker (setup.py): finished with status 'done'
2024-01-24T02:44:17.0838633Z   Created wheel for circuitbreaker: filename=circuitbreaker-1.4.0-py3-none-any.whl size=7522 sha256=d7ca793bbbfaf0c33c67d9e5062e53af029f27b896ef60d91085ebe1189952db
2024-01-24T02:44:17.0844957Z   Stored in directory: /home/runner/.cache/pip/wheels/3c/be/64/266b6ce2ef1130de5e419f04805acbb2df5a4ab1b91348f25b
2024-01-24T02:44:17.0866876Z Successfully built terminaltables circuitbreaker
2024-01-24T02:44:17.5964667Z Installing collected packages: wcwidth, terminaltables, circuitbreaker, types-python-dateutil, python-dateutil, prompt-toolkit, jmespath, click, oci, arrow, oci-cli
2024-01-24T02:44:44.0944509Z Successfully installed arrow-1.3.0 circuitbreaker-1.4.0 click-8.0.4 jmespath-0.10.0 oci-2.119.1 oci-cli-3.37.5 prompt-toolkit-3.0.29 python-dateutil-2.8.2 terminaltables-3.1.0 types-python-dateutil-2.8.19.20240106 wcwidth-0.2.13
2024-01-24T02:44:44.2271682Z ##[endgroup]
2024-01-24T02:44:44.5597133Z error from defaultErrorFunction:  {
2024-01-24T02:44:44.5598083Z   response: Response {
2024-01-24T02:44:44.5598733Z     size: 0,
2024-01-24T02:44:44.5599347Z     timeout: 0,
2024-01-24T02:44:44.5600348Z     [Symbol(Body internals)]: { body: [PassThrough], disturbed: false, error: null },
2024-01-24T02:44:44.5601574Z     [Symbol(Response internals)]: {
2024-01-24T02:44:44.5604974Z       url: 'https://containerengine.***.oci.oraclecloud.com/20180222/clusters/***',
2024-01-24T02:44:44.5606175Z       status: 401,
2024-01-24T02:44:44.5606921Z       statusText: 'Unauthorized',
2024-01-24T02:44:44.5607674Z       headers: [Headers],
2024-01-24T02:44:44.5608326Z       counter: 0
2024-01-24T02:44:44.5609693Z     }
2024-01-24T02:44:44.5610237Z   },
2024-01-24T02:44:44.5611498Z   errorObject: OciError: The required information to complete authentication was not provided or was incorrect.
2024-01-24T02:44:44.5614030Z       at Object.handleErrorResponse (/home/runner/work/_actions/oracle-actions/configure-kubectl-oke/v1.3.2/dist/index.js:38207:16)
2024-01-24T02:44:44.5616636Z       at Function.<anonymous> (/home/runner/work/_actions/oracle-actions/configure-kubectl-oke/v1.3.2/dist/index.js:37704:50)
2024-01-24T02:44:44.5618206Z       at Generator.next (<anonymous>)
2024-01-24T02:44:44.5619827Z       at fulfilled (/home/runner/work/_actions/oracle-actions/configure-kubectl-oke/v1.3.2/dist/index.js:37683:58)
2024-01-24T02:44:44.5621624Z       at processTicksAndRejections (node:internal/process/task_queues:96:5) {
2024-01-24T02:44:44.5622770Z     statusCode: 401,
2024-01-24T02:44:44.5623511Z     serviceCode: 'NotAuthenticated',
2024-01-24T02:44:44.5625219Z     opcRequestId: '87C2DC80BA62-11EE-A553-ADA909427/25AA0C358EADDC1908BA0F859F7E2A67/BAAA0557AE93BB3E064DDF4292E0074D',
2024-01-24T02:44:44.5626847Z     targetService: 'ContainerEngine',
2024-01-24T02:44:44.5627733Z     operationName: 'getCluster',
2024-01-24T02:44:44.5628588Z     timestamp: '2024-01-24T02:44:44.233Z',
2024-01-24T02:44:44.5631343Z     requestEndpoint: 'GET https://containerengine.***.oci.oraclecloud.com/20180222/clusters/***',
2024-01-24T02:44:44.5632875Z     clientVersion: 'Oracle-TypeScriptSDK/2.57.0',
2024-01-24T02:44:44.5644395Z     loggingTips: 'To get more info on the failing request, refer to https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/typescriptsdkconcepts.htm#typescriptsdkconcepts_topic_Logging for ways to log the request/response details.',
2024-01-24T02:44:44.5652575Z     troubleshootingTips: "See https://docs.oracle.com/iaas/Content/API/References/apierrors.htm#apierrors_401__401_notauthenticated for more information about resolving this error Also see https://docs.oracle.com/iaas/api/#/en/containerengine/20180222/Cluster/GetCluster for details on this operation's requirements. If you are unable to resolve this ContainerEngine issue, please contact Oracle support and provide them this full error message."
2024-01-24T02:44:44.5657336Z   }
2024-01-24T02:44:44.5658085Z }
2024-01-24T02:44:44.5668129Z Request cannot be retried. Not Retrying. Exception occurred : Error: The required information to complete authentication was not provided or was incorrect.
2024-01-24T02:44:44.5762600Z ##[error]The required information to complete authentication was not provided or was incorrect.
2024-01-24T02:44:44.6295695Z Cleaning up orphan processes`

I don´t even know which configuration is missing or not configured.

**Comment by Djelibeybi** [comment]
The provided credentials do not provide sufficient access to the cluster. So, you need to double check all your secrets are correct. I suggest using the https://github.com/oracle-actions/run-oci-cli-command action to validate this as it uses the same configuration but allows you to unhide the output so you can see what's happening.

**Comment by gustavomr** [comment]
T

> The provided credentials do not provide sufficient access to the cluster. So, you need to double check all your secrets are correct. I suggest using the https://github.com/oracle-actions/run-oci-cli-command action to validate this as it uses the same configuration but allows you to unhide the output so you can see what's happening.

Tried this one but getting the same error here: https://github.com/oracle-actions/run-oci-cli-command/issues/23

**Comment by Djelibeybi** [comment]
Then the credentials you are providing are wrong. That linked issue provided no actual detail, so I cannot help any further.

**Comment by gustavomr** [comment]
Hi, I solved the last problem putting my public key inside my perfil into oracle cloud. 

![image](https://github.com/oracle-actions/configure-kubectl-oke/assets/600478/6f14f7ff-2b9d-49a2-97de-8ff0c948e449)
